# Generated by Django 2.0.2 on 2019-07-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta120_adapter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='key',
            field=models.CharField(default='dummy', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensor',
            name='sensor_id',
            field=models.CharField(default='xxx', max_length=60, unique=True),
            preserve_default=False,
        ),
    ]
