# Generated by Django 2.0.13 on 2019-10-24 13:32

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sensor_id', models.CharField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('sensor_type', models.CharField(max_length=60)),
                ('description', models.TextField(blank=True)),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Thing')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
