# Generated by Django 2.0.13 on 2019-10-24 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gatekeeper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datastream',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='datastream',
            name='thing',
        ),
        migrations.RemoveField(
            model_name='thing',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Datastream',
        ),
        migrations.DeleteModel(
            name='Thing',
        ),
    ]
