# Generated by Django 2.0.2 on 2019-10-23 07:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gatekeeper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.CharField(max_length=70, primary_key=True, serialize=False, verbose_name='id')),
                ('time', models.DateTimeField(verbose_name='time')),
                ('sensor_id', models.CharField(max_length=50, verbose_name='sensor_id')),
                ('property_name', models.CharField(max_length=50, verbose_name='property_name')),
                ('property_value', django.contrib.postgres.fields.jsonb.JSONField()),
                ('datastream', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='gatekeeper.Datastream')),
            ],
        ),
    ]
