# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-26 11:52
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Datastream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sts_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'data stream',
                'verbose_name_plural': 'data streams',
                'permissions': (('view_datastream', 'Can view datastream'), ('create_observation', 'Can create observation to datastream')),
            },
        ),
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sts_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'thing',
                'verbose_name_plural': 'things',
                'permissions': (('view_thing_location', 'Can view thing location'), ('view_thing_location_history', 'Can view thing location history')),
            },
        ),
        migrations.AddField(
            model_name='datastream',
            name='thing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gatekeeper.Thing'),
        ),
    ]
